version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 21 and npm...
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash -
      - sudo yum install -y nodejs
  build:
    commands:
      - npm install --loglevel=error
      - echo Executing database migrations
      - npx sequelize db:create
      - npx sequelize db:migrate
      - codebuild-breakpoint
